server:
  port: 8080
  servlet:
    context-path: "/api/v1"

spring:
#  main:
#    banner-mode: off
#    lazy-initialization: true
  profiles:
    active: dev
  application:
    name: ecommerce-api
  datasource:
    url: ${JDBC_URL:jdbc:mysql://localhost:3306/ecommerce}
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  output:
    ansi:
      enabled: always
  mail:
    host: "smtp.gmail.com"
    port: 587
    username: "dinhtruonghioo4@gmail.com"
    password: "lcjokgdjzuljvzgb"
    properties.mail.smtp:
      auth: true
      starttls.enable: true

#logging:
#  level:
#    root: WARN
#    com.dinchan: INFO
#    org.springframework: WARN
#    org.hibernate: ERROR
#    org.apache.tomcat: ERROR





